import { Event } from '@/types'

// デモデータ（一元管理）
export const demoEvents: Event[] = [
  {
    id: 'demo-1',
    title: '会計ソフトウェア最新トレンドセミナー',
    startAt: new Date('2024-02-15T10:00:00Z'),
    endAt: new Date('2024-02-15T12:00:00Z'),
    type: 'seminar',
    organizer: '会計システム研究会',
    place: '東京国際フォーラム',
    registerUrl: 'https://example.com/register1',
    fee: 5000,
    target: ['会計士', '税理士', '経営者'],
    description: '最新の会計ソフトウェアの機能と導入事例について詳しく解説します。',
    imageUrl: undefined,
    prefecture: '東京都',
    status: 'published',
    createdBy: 'demo-user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-2',
    title: 'ファイナンス・テック勉強会',
    startAt: new Date('2024-02-20T19:00:00Z'),
    endAt: new Date('2024-02-20T21:00:00Z'),
    type: 'meetup',
    organizer: 'FinTechコミュニティ',
    place: '渋谷スクランブルスクエア',
    registerUrl: 'https://example.com/register2',
    fee: 0,
    target: ['エンジニア', 'ファイナンス関係者'],
    description: 'ブロックチェーン技術とファイナンスの融合について議論します。',
    imageUrl: undefined,
    prefecture: '東京都',
    status: 'published',
    createdBy: 'demo-user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-3',
    title: '税務申告実務ワークショップ',
    startAt: new Date('2024-02-25T14:00:00Z'),
    endAt: new Date('2024-02-25T17:00:00Z'),
    type: 'workshop',
    organizer: '税理士法人サポート',
    place: '大阪ビジネスパーク',
    registerUrl: 'https://example.com/register3',
    fee: 8000,
    target: ['税理士', '会計士', '経理担当者'],
    description: '実務で使える税務申告のテクニックをワークショップ形式で学びます。',
    imageUrl: undefined,
    prefecture: '大阪府',
    status: 'published',
    createdBy: 'demo-user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-4',
    title: 'オンライン会計実務セミナー',
    startAt: new Date('2024-03-01T13:00:00Z'),
    endAt: new Date('2024-03-01T15:00:00Z'),
    type: 'webinar',
    organizer: 'オンライン会計協会',
    place: 'オンライン',
    registerUrl: 'https://example.com/register4',
    fee: 3000,
    target: ['会計士', '税理士', '経理担当者'],
    description: 'オンラインでの会計実務について詳しく解説します。',
    imageUrl: undefined,
    prefecture: '全国',
    status: 'published',
    createdBy: 'demo-user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'demo-5',
    title: '新規会計士向けセミナー',
    startAt: new Date('2024-03-10T09:00:00Z'),
    endAt: new Date('2024-03-10T17:00:00Z'),
    type: 'seminar',
    organizer: '新規会計士支援センター',
    place: '名古屋国際会議場',
    registerUrl: 'https://example.com/register5',
    fee: 15000,
    target: ['新規会計士', '会計士志望者'],
    description: '新規会計士のための実務セミナーです。',
    imageUrl: undefined,
    prefecture: '愛知県',
    status: 'published',
    createdBy: 'demo-user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
] 